---
title: "Foregrounding/Backgrounding"
author: "Claire Bergey and Dan Yurovsky"
date: '`r Sys.Date()`'
output:
  html_document:
    highlight: tango
    theme: sandstone
    code_folding: hide
    toc: false
    toc_float: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-libraries, library, message=F, results='hide', warning=FALSE}
library(tidyverse)
library(here)
library(knitr)
library(tidyboot)
library(lme4)
library(broom.mixed)
library(RColorBrewer)

theme_set(theme_classic(base_size = 16))
```

```{r read-data,  message = FALSE, warning = FALSE}
data <- read_csv(here("data/foregroundingv3-7.csv")) %>%
  filter(subid != 0, subage != 0, subid != "subid") %>%
  filter(subid != 18, subid != 19, subid != 21, subid != 22, subid != 23, subid != 4, subid != 27, subid != "CS000") %>%
  mutate(testinglocation = ifelse(grepl("CS",subid),"CS","MSI"), 
         subid = ifelse(grepl("CS",subid),paste0("1",subid),subid),
         subid = str_remove(subid,"CS"),
         chosetarget = as.logical(chosetarget),
         subid = paste0(subage, "_", subid)) %>%
  mutate_at(c("subage","counter"), as.numeric)

```

```{r plot_data}
mean_data <- data %>%
  mutate(agebin = subage > 4,
         agebin = factor(agebin, levels = c(F, T), 
                             labels = c("young", "old"))) %>%
  group_by(modifier, response, agebin, subid) %>%
  summarise(chosetarget = mean(chosetarget)) %>%
  tidyboot_mean(chosetarget) 

mean_data_nofacets <- data %>%
  #filter(counter <= 4) %>%
  group_by(modifier, response, subid) %>%
  summarise(chosetarget = mean(chosetarget)) %>%
  tidyboot_mean(chosetarget) 

mean_data_nofacets %>%
  ggplot(aes(x = modifier, y = empirical_stat, fill = response)) + 
  geom_col(stat = "identity",
                      position = position_dodge()) +
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper),
                 position = position_dodge(0.9)) +
  scale_fill_manual(values=c("#a28a82ff", "#60270cff"))


mean_data %>%
  ggplot(aes(x = modifier, y = empirical_stat, fill = response)) + 
  geom_col(stat = "identity",
                      position = position_dodge()) +
  geom_linerange(aes(ymin = ci_lower, ymax = ci_upper),
                 position = position_dodge(0.9)) +
  scale_fill_brewer(palette = "Purples") +
  facet_grid(~ agebin)
   

```



```{r}

rt_means <- data %>%
  mutate(rtsearch = log(as.numeric(rtsearch))) %>%
  mutate(agebin = subage > 4,
         agebin = factor(agebin, levels = c(F, T), 
                             labels = c("young", "old"))) %>%
  group_by(modifier, response, agebin, subid) %>%
  summarise(rtsearch = mean(rtsearch)) %>%
  tidyboot_mean(rtsearch) 

rt_means %>%
  ggplot(aes(x = modifier, y = empirical_stat, color = response)) + 
  # geom_col(stat = "identity",
                     # position = position_dodge()) +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper),
                 position = position_dodge(0.9)) +
  scale_fill_brewer(palette = "Purples") +
  facet_grid(~agebin)


```


```{r model}
model1 <- data %>%
  #mutate(age_bin = subage > 4) %>%
  glmer(chosetarget ~ modifier * response + (1|subid),
        family = "binomial", data = .) %>%
  tidy() %>%
  filter(effect == "fixed") %>%
  select(-effect, - group) %>%
  kable()

model2 <- data %>%
  #filter(counter <= 4) %>%
  #mutate(age_bin = subage > 4) %>%
  glmer(chosetarget ~ modifier + response + (1|subid),
        family = "binomial", data = .) %>%
  tidy() %>%
  filter(effect == "fixed") %>%
  select(-effect, - group) %>%
  kable()

data %>%
  filter(counter <= 4) %>%
  mutate(rtsearch = log(as.numeric(rtsearch)),
         modifier = factor(modifier, levels = c("nomodifier", "new")),
         response = factor(response, levels = c("yes", "no"))) %>%
  #mutate(age_bin = subage > 4) %>% 
  lmer(rtsearch ~ modifier * response + (1|subid), data = .) %>%
  tidy() %>%
  filter(effect == "fixed") %>%
  select(-effect, - group) %>%
  kable()

oldkidsmodel <- data %>%
  filter(subage > 4) %>%
  glmer(chosetarget ~ modifier * response + (1|subid),
        family = "binomial", data = .) %>%
  tidy() %>%
  filter(effect == "fixed") %>%
  select(-effect, - group) %>%
  kable()
```

